<a href="https://colab.research.google.com/github/sandeepgundeboina/Preppin-Data/blob/main/PreppIn2k25W2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
d1=pd.read_csv('/content/drive/MyDrive/Abc/preppin24W2/PD 2024 Wk 1 Output Flow Card.csv')
d2=pd.read_csv('/content/drive/MyDrive/Abc/preppin24W2/PD 2024 Wk 1 Output Non-Flow Card.csv')

In [3]:
df=pd.concat([d1,d2],axis=0)
df.head()

,Date,Flight Number,From,To,Class,Price,Flow Card?,Bags Checked,Meal Type
0,22/07/2024,PA010,Tokyo,New York,Economy,2380.0,Yes,0,Egg Free
1,20/04/2024,PA002,New York,London,Economy,3490.0,Yes,1,Vegan
2,23/01/2024,PA010,Tokyo,New York,Premium Economy,825.0,Yes,1,Vegetarian
3,05/06/2024,PA006,Tokyo,London,First Class,618.0,Yes,3,Vegan
4,30/03/2024,PA004,Perth,London,First Class,446.0,Yes,1,Nut Free

In [4]:
df.dtypes

Date              object
Flight Number     object
From              object
To                object
Class             object
Price            float64
Flow Card?        object
Bags Checked       int64
Meal Type         object
dtype: object

    Converting date column to datetime data type

In [5]:
df['Date']=pd.to_datetime(df['Date'],dayfirst=True)
df.dtypes

Date             datetime64[ns]
Flight Number            object
From                     object
To                       object
Class                    object
Price                   float64
Flow Card?               object
Bags Checked              int64
Meal Type                object
dtype: object

    COnverting to Periods and getting quarter wise data based on year

In [6]:
df['Quarter']=pd.PeriodDtype(freq='Q')
df['Quarter']=df['Date'].dt.to_period('Q')
df.head()

,Date,Flight Number,From,To,Class,Price,Flow Card?,Bags Checked,Meal Type,Quarter
0,2024-07-22,PA010,Tokyo,New York,Economy,2380.0,Yes,0,Egg Free,2024Q3
1,2024-04-20,PA002,New York,London,Economy,3490.0,Yes,1,Vegan,2024Q2
2,2024-01-23,PA010,Tokyo,New York,Premium Economy,825.0,Yes,1,Vegetarian,2024Q1
3,2024-06-05,PA006,Tokyo,London,First Class,618.0,Yes,3,Vegan,2024Q2
4,2024-03-30,PA004,Perth,London,First Class,446.0,Yes,1,Nut Free,2024Q1

    Grouping data and pivoting and resetting index

In [7]:
max=df.groupby(['Flow Card?','Quarter','Class'])['Price'].max().reset_index().pivot(index=['Flow Card?','Quarter'],columns='Class',values='Price').reset_index()
min=df.groupby(['Flow Card?','Quarter','Class'])['Price'].min().reset_index().pivot(index=['Flow Card?','Quarter'],columns='Class',values='Price').reset_index()
median=df.groupby(['Flow Card?','Quarter','Class'])['Price'].median().reset_index().pivot(index=['Flow Card?','Quarter'],columns='Class',values='Price').reset_index()

    Merging all data

In [8]:
Dall=pd.concat([max,min,median],axis=0)
Dall.head()

Class,Flow Card?,Quarter,Business Class,Economy,First Class,Premium Economy
0,No,2024Q1,834.0,3455.0,699.0,1702.5
1,No,2024Q2,828.0,3480.0,694.0,1745.0
2,No,2024Q3,838.8,3475.0,691.0,1747.5
3,No,2024Q4,835.2,3465.0,698.0,1730.0
4,Yes,2024Q1,840.0,3500.0,698.0,1737.5

    Changing column names and downloading as CSV

In [9]:
Dall=Dall.rename(columns={'Business Class':'Premium','Economy':'First','First Class':'Economy','Premium Economy':'Business'})
Dall.to_csv('/content/sample_data/total_data.csv')

**End Of Code**