In [1]:
import pandas as pd
import numpy as np

In [2]:
swc=pd.read_csv('/content/drive/MyDrive/Abc/Swift Codes.csv')
tr=pd.read_csv('/content/drive/MyDrive/Abc/Transactions.csv')

tr['Account Number']=tr['Account Number'].apply(str)

print(swc.dtypes,'\n')
print(tr.dtypes)

Bank            object
SWIFT code      object
Check Digits    object
dtype: object

Transaction ID     int64
Account Number    object
Sort Code         object
Bank              object
dtype: object

In [3]:
tr['Sort Code']=tr['Sort Code'].str.replace('-','')

In [4]:
tr1=pd.merge(tr,swc,left_on='Bank', right_on='Bank',how="right")

In [5]:
tr1['Country Code']='GB'

In [6]:
tr1['IBAN code']=tr1[['Country Code','Check Digits','SWIFT code','Sort Code','Account Number']].apply(lambda x: "".join(x), axis =1)

In [7]:
df=tr1[['Transaction ID','IBAN code']]
df

    Transaction ID               IBAN code
0             4870  GBC1LOYD51074179724968
1             1126  GBC1LOYD45825569969270
2             8453  GBC1LOYD64945830335066
3             5955  GBC1LOYD97849671124764
4             8500  GBC1LOYD87493846967961
..             ...                     ...
95            4063  GB12DSBX28178620220923
96            3770  GB12DSBX32549026013637
97            2760  GB12DSBX28066085744933
98            9530  GB12DSBX70700574379515
99            6764  GB12DSBX29723910570182

[100 rows x 2 columns]