In [1]:
import pandas as pd
import numpy as np
import calendar

In [2]:
df={}
xls = pd.ExcelFile('/content/drive/MyDrive/Copy of New Customers.xlsx')
s2=[]
s2=pd.DataFrame(s2,columns=['ID','Joining Date','Account Type','Date of Birth','Ethnicity'])
for x in range(1,13):
   df['X_'+calendar.month_name[x]]=xls.parse(x-1)
   df['X_'+calendar.month_name[x]]['Month']=x
   df['X_'+calendar.month_name[x]]['Year']='2023'
   df['X_'+calendar.month_name[x]]['Joining Date']=df['X_'+calendar.month_name[x]]['Joining Day'].astype(str)+'/'+df['X_'+calendar.month_name[x]]['Month'].astype(str)+'/'+df['X_'+calendar.month_name[x]]['Year']
   df['X_'+calendar.month_name[x]]=df['X_'+calendar.month_name[x]].drop(['Joining Day','Month','Year'],axis=1)
   df['X_'+calendar.month_name[x]]['ID']=df['X_'+calendar.month_name[x]]['ID'].astype(str)
   df1=df['X_'+calendar.month_name[x]]
   s1=df1.pivot(index=['ID','Joining Date'], columns=['Demographic'], values='Value').reset_index().rename_axis(None, axis=1)
   s2=pd.concat([s2,s1],ignore_index=True)

In [3]:
s2

         ID Joining Date Account Type Date of Birth Ethnicity
0    102704    23/1/2023        Basic      3/9/2000     Black
1    119237    15/1/2023     Platinum     9/18/2012     Other
2    139746    19/1/2023         Gold     2/27/1948     Black
3    155713    12/1/2023     Platinum      7/3/2009     White
4    174968    10/1/2023     Platinum     9/30/1980     Other
..      ...          ...          ...           ...       ...
985  968967    7/12/2023         Gold    12/24/1992     Asian
986  970548   12/12/2023     Platinum      5/9/1996     Asian
987  973596   16/12/2023     Platinum     2/22/1971     Other
988  983034    6/12/2023     Platinum    11/13/1972     Asian
989  983979   27/12/2023        Basic      5/4/1954     White

[990 rows x 5 columns]

###END OF CODE