In [1]:
import pandas as pd
import numpy as np

In [2]:
data=pd.read_csv('/content/drive/MyDrive/Abc/PD 2023 Wk 1 Input.csv')

In [3]:
data['Transaction Date'] = pd.to_datetime(data['Transaction Date'])

In [4]:
data['Bank']=data['Transaction Code'].str.split(pat='-',expand=True).get(0)
data['Online or In-Person']=data['Online or In-Person'].replace([1,2],['Online','In-Person'])
data

,Transaction Code,Value,Customer Code,Online or In-Person,Transaction Date,Bank
0,DTB-716-679-576,1448,100001,In-Person,2023-03-20,DTB
1,DS-795-814-303,7839,100001,In-Person,2023-11-15,DS
2,DSB-807-592-406,5520,100005,Online,2023-07-14,DSB
3,DS-367-545-264,7957,100007,In-Person,2023-08-18,DS
4,DSB-474-374-857,5375,100000,In-Person,2023-08-26,DSB
...,...,...,...,...,...,...
360,DTB-116-439-102,6708,100001,Online,2023-01-29,DTB
361,DS-849-981-514,8500,100000,In-Person,2023-10-29,DS
362,DS-726-686-279,9455,100006,In-Person,2023-10-08,DS
363,DS-551-937-380,475,100002,Online,2023-11-10,DS
364,DS-976-542-770,7364,100009,Online,2023-09-10,DS

In [5]:
df=data[data['Bank']=='DSB']
df['Quarter'] = df['Transaction Date'].dt.quarter

<ipython-input-5-f4b6d7389fb5>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Quarter'] = df['Transaction Date'].dt.quarter

In [6]:
sol=df.groupby(by=['Online or In-Person','Quarter'])['Value'].sum().reset_index(name='Value').rename(columns={'level_1':'Quarter'})

In [7]:
target=pd.read_csv('/content/drive/MyDrive/Abc/Targets.csv')
target=target.set_index(['Online or In-Person']).stack().reset_index(name='Target').rename(columns={'level_1':'Quarter'})
target['Quarter']=target['Quarter'].replace(['Q1','Q2','Q3','Q4'],[1,2,3,4])

In [8]:
tr1= sol.merge(target, on=['Online or In-Person','Quarter'])

In [9]:
tr1['Varince to Traget']=tr1['Value']-tr1['Target']
tr1.sort_values(by="Varince to Traget",ascending=False)

  Online or In-Person  Quarter  Value  Target  Varince to Traget
5              Online        2  94860   70000              24860
2           In-Person        3  84048   70000              14048
1           In-Person        2  81627   70000              11627
7              Online        4  57520   60000              -2480
6              Online        3  56617   60000              -3383
3           In-Person        4  52832   60000              -7168
4              Online        1  55870   72500             -16630
0           In-Person        1  47115   75000             -27885

End of Code